// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdxtockgbzmpxjpxtyed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkeHRvY2tnYnptcHhqcHh0eWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDA0ODEsImV4cCI6MjA3MzYxNjQ4MX0.i1ZgL1TW43ZM0g6_iEQxjBIS3JIv9h_9Y3Fe8AB4thY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});